/**
 * index.ts — public barrel export.
 *
 * `import { WhatsApp, filterText, ... } from 'jswa'`
 */

export { WhatsApp } from './client.js'
export type {
  Config,
  SendMessageOptions,
  SendMediaOptions,
  SendReactionOptions,
  RemoveReactionOptions,
  SendLocationOptions,
  SendContactOptions,
  SendTemplateOptions,
  SendCatalogOptions,
  SendProductOptions,
  SendProductsOptions,
  SendCarouselOptions,
  RequestContactInfoOptions,
  UpdateBusinessProfileOptions,
  CreateTemplateOptions,
  CreateFlowOptions,
  InitiateCallOptions,
  UpdateConversationalAutomationOptions,
  GetTemplatesOptions,
  UpdateTemplateOptions,
  UpdateFlowMetadataOptions,
  UpsertAuthTemplateOptions,
  UpdateBusinessPhoneNumberSettingsOptions,
  CreateGroupOptions,
  UpdateGroupSettingsOptions,
  PinMessageOptions,
  SetUsernameOptions,
  UpdateBusinessAccountSettingsOptions,
  FlowMetricOptions,
  FlowRequestHandlerFunc,
} from './client.js'

export { GraphAPI } from './api.js'

export {
  WhatsAppError,
  getErrorKind,
  whatsAppErrorFromMap,
  NoClientError,
  NoWebhookError,
  ListenerTimeout,
  ListenerCanceled,
  ListenerStopped,
} from './errors.js'
export type { WhatsAppErrorData, ErrorKind } from './errors.js'

export {
  BaseUpdate,
  Message,
  CallbackButton,
  CallbackSelection,
  FlowCompletion,
  CallPermissionUpdate,
} from './update.js'
export type { MediaInput } from './update.js'

export {
  and,
  or,
  not,
  always,
  never,
  filterText,
  filterImage,
  filterVideo,
  filterAudio,
  filterVoice,
  filterDocument,
  filterSticker,
  filterLocation,
  filterContacts,
  filterReaction,
  filterReply,
  filterForwarded,
  filterMedia,
  filterFromWaId,
  filterTextContains,
  filterTextPrefix,
  filterCallbackData,
  filterCallbackPrefix,
  filterStatusSent,
  filterStatusDelivered,
  filterStatusRead,
  filterStatusFailed,
} from './filters.js'
export type { Filter } from './filters.js'

export { HandlerList } from './handlers.js'
export type { HandlerCallback, HandlerEntry } from './handlers.js'

export { ListenerRegistry, listen } from './listeners.js'
export type { ListenOptions, ListenerKey } from './listeners.js'

export { validateSignature, WebhookProcessor } from './webhook.js'
export type { ProcessResult, WebhookProcessorDeps } from './webhook.js'

export {
  Result,
  User,
  contactToDict,
  sectionListToDict,
  productsSectionToDict,
  commandToDict,
  sessionDescriptionToDict,
  carouselCardToDict,
  paginationToQuery,
  removeGroupParticipant,
} from './types.js'
export type {
  Metadata,
  MessageType,
  Location,
  Reaction,
  ReplyToMessage,
  Referral,
  OrderItem,
  Order,
  Unsupported,
  ContactPhone,
  ContactEmail,
  ContactURL,
  ContactAddress,
  ContactName,
  ContactOrg,
  Contact,
  MediaBase,
  Image,
  Video,
  Audio,
  Document,
  Sticker,
  MediaURL,
  Button,
  URLButton,
  VoiceCallButton,
  SectionRow,
  Section,
  SectionList,
  ProductsSection,
  FlowButton,
  MessageStatusType,
  MessageStatus,
  BusinessProfile,
  BusinessPhoneNumber,
  BusinessPhoneNumberSettings,
  CommerceSettings,
  QRCode,
  FlowStatus,
  FlowCategory,
  CreatedFlow,
  FlowDetails,
  FlowRequest,
  FlowResponse,
  FlowMetricName,
  FlowMetricGranularity,
  TemplateCategory,
  TemplateStatus,
  CreatedTemplate,
  TemplateDetails,
  TemplateParam,
  SentMessage,
  SentMediaMessage,
  SentReaction,
  SentLocationRequest,
  SentTemplate,
  SentContactInfoRequest,
  PhoneNumberChange,
  IdentityChange,
  ChatOpened,
  TemplateStatusUpdate,
  TemplateCategoryUpdate,
  TemplateQualityUpdate,
  TemplateComponentsUpdate,
  UserMarketingPreferences,
  CallStatus,
  CallConnect,
  CallTerminate,
  CallPermissionRequestButton,
  SessionDescription,
  InitiatedCall,
  CallPermissionsResult,
  Pagination,
  WhatsAppBusinessAccount,
  SuccessResult,
  BlockedUser,
  UsersBlockedResult,
  UnblockedUser,
  UsersUnblockedResult,
  Command,
  RawUpdate,
  StorageConfiguration,
  CallingSettings,
  GroupJoinApprovalMode,
  GroupOperation,
  GroupParticipant,
  GroupDetails,
  GroupInviteLink,
  GroupJoinRequest,
  UsernameStatusType,
  UsernameStatus,
  CarouselButtons,
  ImageCarouselCard,
  VideoCarouselCard,
  CarouselCard,
  TemplateArchiveEntry,
  ArchiveTemplatesResult,
  UnarchiveTemplatesResult,
  CreatedBusinessPhoneNumber,
} from './types.js'
